name: job2
on:
 push:
   branches:
      - main
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    
     - uses: convictional/trigger-workflow-and-wait@master
       with:
        owner: vkele12
        repo: repo1
        github_token: ${{ secrets.ACTION_KEY }}
        workflow_file_name: job1.yml
     #   ref: master
     - name: Display message
       run: echo "How are you"
         
