name: Deploy1
on:
 push:
   branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
     - name: Build Web App
       run: |
        echo "build we app"
        sleep 10s
     - uses: convictional/trigger-workflow-and-wait@master
       with:
        owner: vkele12
        repo: repo1
        github_token: ${{ secrets.ACTION_KEY }}
        workflow_file_name: master.yml
     #   ref: master
     - name: Deploy web app
       run: |
         echo "Deploy web app1 12345"
         sleep 10s
