name: Deploy1
on:
 push:
   branches:
      - main
jobs:
  build:
   
    runs-on: ubuntu-latest
    steps:
     - name: Display message
       run: echo " Hi there "
       
     - uses: convictional/trigger-workflow-and-wait@master
       with:
        owner: vkele12
        repo: repo1
        github_token: ${{ secrets.ACTION_KEY }}
        workflow_file_name: master.yml
    
     - name: Display anothere message
       run: echo "How are you doing"
        
